version: '3.1'

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node
    depends_on:
      - app
  db:
    build: 
      context: ./mysql
    image: mysql:8.2.0
    container_name: proxy-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node
  app:
    build:
      context: ./node
    container_name: proxy-app
    networks:
      - node
    ports:
      - "3000:3000"
    volumes:
      - ./node/src:/node/app
    depends_on:
      - db

networks:
  node:
    driver: bridge